apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "tomcat-helloworld", "namespace": "my-tomcat-app", "kind": "DeploymentConfig"}]'
  creationTimestamp: null
  labels:
    app: jenkins-pipeline-development
    name: tomcat-s2i-jenkins-pipeline
    template: application-template-development-pipeline
  name: tomcat-s2i-jenkins-pipeline
spec:
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
       pipeline {
         agent any
         stages {
           stage('before-build') {
               steps {
                   script {
                       openshift.withCluster() {
                           openshift.withProject("my-tomcat-app") {
                               echo "Using project: ${openshift.project()}"
                           }
                       }
                   }
               }
           }
           stage('build') {
               steps ("step-1"){
                   script {
                       openshift.withCluster() {
                           openshift.withProject("my-tomcat-app") {
                               echo "Using project: ${openshift.project()}"
                               def bld = openshift.startBuild("tomcat-helloworld")
                           }
                       }
                   }
               }
           }
           stage('after-build') {
             steps {
               script {
                   script {
                       openshift.withCluster() {
                           openshift.withProject() {
                               echo "Using project: ${openshift.project()}"
                           }
                       }
                   }
               }
             }
           }
         }
       }
    type: JenkinsPipeline
  triggers:
  - github:
      secret: secret101
    type: GitHub
  - generic:
      secret: secret101
    type: Generic
status:
  lastVersion: 0
