apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "tomcat-helloworld", "namespace": "my-tomcat-app", "kind": "DeploymentConfig"}]'
  creationTimestamp: null
  labels:
    app: jenkins-pipeline-development
    name: s2itomcat-development-pipeline
    template: application-template-development-pipeline
  name: s2itomcat-development-pipeline
spec:
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node {
        stage 'build'
        openshiftBuild(buildConfig: 'tomcat-helloworld', showBuildLogs: 'true', namespace: 'my-tomcat-app')
        stage 'deploy'
        openshiftDeploy(deploymentConfig: 'tomcat-helloworld', namespace: 'my-tomcat-app')
        }
    type: JenkinsPipeline
  triggers:
  - github:
      secret: secret101
    type: GitHub
  - generic:
      secret: secret101
    type: Generic
status:
  lastVersion: 0